name: elc
channels:
  - conda-forge
  - pytorch3d
  - iopath
  - fvcore
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pip:
      - absl-py==1.4.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - asttokens==2.2.1
      - async-timeout==4.0.2
      - attrs==23.1.0
      - blis==0.7.9
      - cachetools==5.3.0
      - catalogue==2.0.8
      - certifi==2022.12.7
      - charset-normalizer==3.1.0
      - click==8.1.3
      - cmake==3.26.3
      - colorama==0.4.6
      - confection==0.0.4
      - cymem==2.0.7
      - executing==1.2.0
      - filelock==3.12.0
      - frozenlist==1.3.3
      - fsspec==2023.4.0
      - future==0.18.3
      - google-auth==2.17.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.54.0
      - huggingface-hub==0.13.4
      - icecream==2.1.3
      - idna==3.4
      - importlib-metadata==6.5.0
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonlines==3.1.0
      - langcodes==3.3.0
      - lit==16.0.1
      - markdown==3.4.3
      - markupsafe==2.1.2
      - mpmath==1.3.0
      - multidict==6.0.4
      - murmurhash==1.0.9
      - networkx==3.1
      - numpy==1.24.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - packaging==23.1
      - pandas==2.0.0
      - pathy==0.10.1
      - pillow==9.5.0
      - preshed==3.0.8
      - protobuf==4.22.3
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pydantic==1.10.7
      - pydeprecate==0.3.0
      - pygments==2.15.1
      - pytextrank==3.1.1
      - python-dateutil==2.8.2
      - pytorch-lightning==1.3.8
      - pytz==2023.3
      - pyyaml==5.4.1
      - regex==2023.3.23
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - six==1.16.0
      - smart-open==6.3.0
      - spacy==3.5.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.4
      - srsly==2.4.6
      - sympy==1.11.1
      - tensorboard==2.12.2
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - thinc==8.1.9
      - threadpoolctl==3.1.0
      - tokenizers==0.13.3
      - torch==2.0.0
      - torchmetrics==0.3.2
      - tqdm==4.65.0
      - transformers==4.28.1
      - triton==2.0.0
      - typer==0.7.0
      - typing-extensions==4.5.0
      - tzdata==2023.3
      - urllib3==1.26.15
      - wasabi==1.1.1
      - werkzeug==2.2.3
      - yarl==1.8.2
      - zipp==3.15.0
